name: conventionalcommits-semantic-releasing
description: Semantic Release Action using Conventional Commits
author: Martina Baiardi

inputs:
  token:
    description: 'Personal Access token with push permissions on repository'
    required: true
  test:
    description: 'A test param'
    required: true
    default: 'testing-default' 

runs:
    using: composite
    steps:
      - shell: bash
        run: echo ${{ inputs.test }}
      
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
        with:
          token: ${{ inputs.token }}
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Import Configuration files
        shell: bash
        run: |
          cd $GITHUB_ACTION_PATH
          cp package.json $GITHUB_WORKSPACE
          node --version
          cp .releaserc.yml $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git pull



      - name: Install npm package
        shell: bash
        run: npm install

      - name: Perform release
        shell: bash
        env: 
          GITHUB_TOKEN: ${{ inputs.token }}
        run: npx semantic-release  
branding:
  icon: 'tag'
  color: 'green'
          
