name: conventionalcommits-semantic-releasing
description: Semantic Release Action that automatically computes version using Conventional Commits
author: Martina Baiardi

inputs:
  token:
    description: 'Personal Access token with push permissions on repository'
    required: true
  publish-command:
    description: 'A custom shell command executed during the publication of the new version'
    required: false
    default: ''
  assets-path:
    description: 'The path that will be loaded into release assets'
    required: false
    default: 'assets/**'

runs:
    using: composite
    steps:
      - name: Import Configuration files
        shell: bash
        run: |
          cp $GITHUB_ACTION_PATH/package.json ./
          cp $GITHUB_ACTION_PATH/release.config.js ./
      - name: Find the version of Node from package.json
        id: node-version
        shell: bash
        run: echo "version=$(jq -r .engines.node ./package.json)" >> $GITHUB_OUTPUT
      - run: echo ${{ steps.node-version.outputs.version }}
        shell: bash
      - name: Install Node
        uses: actions/setup-node@v6.2.0
        with:
          node-version: ${{ steps.node-version.outputs.version }}
          check-latest: true
      - name: Install npm package
        shell: bash
        run: npm install

      - name: Perform release
        shell: bash
        env: 
          GITHUB_TOKEN: ${{ inputs.token }}
          PUBLISH_COMMAND: ${{ inputs.publish-command }}
          ASSETS_PATH: ${{ inputs.assets-path }}
        run: npx semantic-release
branding:
  icon: 'tag'
  color: 'green'

