name: conventionalcommits-semantic-releasing
description: Semantic Release Action using Conventional Commits
author: Martina Baiardi

inputs:
  token:
    description: 'Personal Access token with push permissions on repository'
    required: true
  publish-command:
    description: 'A custom shell command executed during the publication of the new version'
    required: false
    default: ''
  assets-path: 
    description: 'The path that will be loaded into release assets'
    required: false
    default: 'assets/**'

runs:
    using: composite
    steps:
      - shell: bash
        run: echo ${{ inputs.test }}
      
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
        with:
          token: ${{ inputs.token }}

      - name: Find the version of Node from package.json
        id: node-version
        run: echo "version=$(jq -r .engines.node package.json)" >> $GITHUB_OUTPUT
      - name: Install Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ steps.node-version.outputs.version }}
      
      - name: Import Configuration files
        shell: bash
        run: |
          cd $GITHUB_ACTION_PATH
          cp package.json $GITHUB_WORKSPACE
          node --version
          cp release.config.js $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git pull

      - name: Install npm package
        shell: bash
        run: npm install

      - name: Perform release
        shell: bash
        env: 
          GITHUB_TOKEN: ${{ inputs.token }}
          PUBLISH_COMMAND: ${{ inputs.on-publish-custom-command }}
          ASSETS_PATH: ${{ inputs.publish-assets-path }}
        run: npx semantic-release
branding:
  icon: 'tag'
  color: 'green'
          
