name: Checkout and Release

on:
  push:
    branches: 
      - main
      - master
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
    branches: 
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - name: run action
        uses: anitvam/conventionalcommit-semantic-releasing@v0.5.12
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
